### ISSUE TITLE
Independent Publisher 2: Audio player with broken style

### ISSUE THREAD

**Issue by gabrielbonifacio** [Automattic/themes#4159]
## Steps to replicate

1. Create or edit a page using the Classic Editor.
2. Insert an audio file using the `[audio]` shortcode:

![Audio file](https://i.imgur.com/oWiaDif.png)

3. Save the page.
4. Active the "Independent Publisher 2" theme.

## Result

The styles of the play and volume buttons are broken:

![](https://i.imgur.com/2aJE62u.png)

## Expected

It's expected that the audio player shows up correctly, like the screenshot below:

![image](https://user-images.githubusercontent.com/20730704/124366629-8c437b00-dc27-11eb-8f26-a50f778639d5.png)

These are the declaration blocks from the theme stylesheet that are causing the issue:

```css
.button, .more-link, button:not(.menu-toggle), input[type=button], input[type=reset], input[type=submit], .posts-navigation .nav-links a, #content #infinite-handle span button {
    display: inline-block;
    box-sizing: content-box;
    padding: .4375em .875em;
    cursor: pointer;
    -webkit-transition: background .12s ease-in-out,box-shadow .12s ease-in-out;
    transition: background .12s ease-in-out,box-shadow .12s ease-in-out;
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Oxygen-Sans","Ubuntu","Cantarell","Helvetica Neue",sans-serif;
    font-size: 16px;
    font-weight: 400;
    font-style: normal;
    text-decoration: none;
    color: #fff;
    border: solid 1px transparent;
    border-radius: 3px;
    background: #0087be;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

```css
.button:hover, .more-link:hover, button:not(.menu-toggle):hover, input[type=button]:hover, input[type=reset]:hover, input[type=submit]:hover, .posts-navigation .nav-links a:hover, #content #infinite-handle span button:hover {
    text-decoration: none;
    color: #fff;
    background: #767676;
}
```

```css
.button:focus, .button:active, .more-link:focus, .more-link:active, button:not(.menu-toggle):focus, input[type=button]:focus, input[type=reset]:focus, input[type=submit]:focus, .posts-navigation .nav-links a:focus, #content #infinite-handle span button:focus, button:not(.menu-toggle):active, input[type=button]:active, input[type=reset]:active, input[type=submit]:active, .posts-navigation .nav-links a:active, #content #infinite-handle span button:active {
    outline: 0;
    background: #767676;
    box-shadow: inset 0 2px 2px rgb(0 0 0 / 25%), 0 0 0 6px rgb(0 0 0 / 8%);
}
```

Disabling the declarations above seems to completely fix the problem.

* User report: 4112809-zd-woothemes
* Issue also mentioned on this P2: pd4QKa-6Q-p2
