### ISSUE TITLE
Ixion: Header Search Not Keyboard Accessible

### ISSUE THREAD

**Issue by mrwweb** [Automattic/themes#498]
## Steps to replicate

Confirmed in latest Chrome and Firefox on Windows 10 using [Ixion demo](https://ixiondemo.wordpress.com/?demo).

1. Open site using Ixion.
1. Hit `TAB` repeatedly. You should go past the skip link and all social icons.
1. The search form is skipped and focus goes from last social icon to the site logo

## Result

The built-in search form cannot be accessed by anyone using a keyboard.

## Expected

Search form is in the `TAB` order of the header.

## Potential Fixes

I can see that someone attempted to make it keyboard accessible. However, hidden items can't receive focus, so the existing styles that rely on `.search-field:focus` don't work.

I fixed this by adding `taxindex="0"` to the `label` in `searchform.php` so that the label can receive focus and then adding these CSS rules:

```css
.site-header .search-form label:focus .search-form-icon::before {
	transform: translateX(-300px);
	transition: 0.3s ease;
}
.site-header .search-form label:focus .search-field {
	width: 300px;
	transition: .3s ease;
	visibility: visible;
}
```

The downside of this solution is that it adds an extra `TAB` stop—you have to go to the `label` first, then the `input`.
