### ISSUE TITLE
Livro: button color impossible to override

### ISSUE THREAD

**Issue by markhowellsmead** [Automattic/themes#5693]
## Steps to replicate

- Use the color palette settings in FSE to change the default text color of all button blocks.
- The CSS is applied and the button looks correct in the editor and in the customizer preview. But the text remains black on the frontend of the website.
- Overriding the color on each individual block works correctly.

I suspect that a CSS rule elsewhere in the cascade is overriding the color setting. I couldn't find out where through the Chrome dev console. Deactivating every other CSS rule in the dev console manually (unchecking) didn't make the color work correctly.

## Result

The following CSS is applied. (In the example, the color white has been selected in the styles » color settings for all button blocks.) Although the browser dev console indicates that `color: var(--wp--preset--color--white);` is correctly applied, this is not the color shown.

```css
.wp-block-button__link {
    background-color: var(--wp--preset--color--secondary);
    border-radius: 0;
    color: var(--wp--preset--color--white);
    font-size: var(--wp--preset--font-size--small);
    padding: 1.25em 1.15em 1.15em 1.15em;
    text-transform: uppercase;
}
```

## Expected

The color should respect the setting from the styles » color editor.
