### ISSUE TITLE
[Bug]: Twenty-Eleven Global Styles Not Respected  

### ISSUE THREAD

**Issue by freelylovinglife** [Automattic/themes#6875]
### Quick summary

Some fonts within theme does not display correctly. The Roboto theme specifically displays a lighter version of Roboto on a published page. Editor shows a darker version.  There are other fonts within the theme that also do this like Open Sans.  

### Steps to reproduce

1. Open customize
2. Go to Fonts
3. Choose Roboto or Open Sans as Headings and Base Font
4. Save changes and view live page. 

### What you expected to happen

The editor font should show on live page. 

### What actually happened

The live page font is lighter in color. 

**Editors View**

<img width="829" alt="Screen Shot 2023-02-22 at 6 51 21 PM" src="https://user-images.githubusercontent.com/76487565/220790568-168307e0-8c81-4547-bc81-66d20f064cb9.png">

**Live View**
<img width="694" alt="Screen Shot 2023-02-22 at 6 51 29 PM" src="https://user-images.githubusercontent.com/76487565/220790620-2718d248-d799-4690-a83c-2922f691b5a4.png">

### Browser

Tested in Chrome and Safari

### Platform (Simple, Atomic, or both?)

Simple Site ZD-5964277

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

Possible CSS fix?

**Comment by dragstor** [comment]
As a workaround, I provided the following CSS snippet to the user in 5964277-zen:

```CSS
/* Override the font weight | 5964277-zen (NST) */

html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, 
blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, 
font, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, dl, 
dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, 
tfoot, thead, tr, th, td {
    font-weight: 400;
}

/* END | 5964277-zen (NST) */
```
