### ISSUE TITLE
Independent Publisher 2 - Issues in post view (Gallery layout and font color)

### ISSUE THREAD

**Issue by joaopamaral** [Automattic/themes#7470]
### Quick summary

If a blog is created using the `Independent Publisher 2` theme with a dark palette and a gallery is added to a post, the post may have an unusual layout with incorrect font color when viewed individually. However, the same post may appear with the correct layout when viewed on the home page.

- Home view
![image](https://github.com/Automattic/themes/assets/7281460/292c1ea3-6a9d-4341-8ab7-40dcba9cdd3a)

- Post view
![image](https://github.com/Automattic/themes/assets/7281460/bb77bb38-833d-4ec4-b573-09a2f53940ea)

### Steps to reproduce

1. Create a blog.
2. Change the theme to `Independent Publisher 2`.
3. Change the Appearance> Customizing > Colors & Backgrounds and select the Palette with the dark colors.
4. Create a post with a Gallery Block (add some images to the Gallery).
5. Check the differences between home page and post page.

### What you expected to happen

The post view has the same layout seen in the home view.

### What actually happened

The post layout has some incorrect style (Gallery layout and font color).

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The issue can be fixed if the following CSS is added to the blog.

```css
.entry-title,
.entry-content,
.comment-reply-title,
.widget-title,
.comments-title,
.comment-body,
.comment .comment-meta .comment-author .fn,
.comment .comment-content {
	color: #9B9B9B !important;
}

a {
	color: #ffffff !important;
}

body .is-layout-flex {
	display: flex !important;
}
```
