### ISSUE TITLE
Lovecraft: YouTube embed aspect ratio not honored on mobile

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#8086]
### Quick summary

Embedded YouTube video not displaying correctly on mobile. It crops them into more of a square instead of honoring the aspect ratio.

![pxUJyW.png](https://github.com/user-attachments/assets/6fd9331c-3caa-4bb6-b2f1-43849c21ddd2)

### Steps to reproduce

1. Activate Lovecraft theme
2. Embed a YouTube video
3. View on mobile
4. Change alignment from None to Centered
5. View on mobile

### A clear and concise description of what you expected to happen.

I expected the video to display on mobile with the same aspect ratio as on desktop.

### What actually happened

The block is cropped to more of a square or vertical display.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

There _might_ be some CSS that could fix this, but I wasn't able to come up with it.

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

I tested on the Assembler theme and it works as expected.

**Comment by arthur791004** [comment]
The following styles are missing

```css
.wp-embed-responsive .wp-has-aspect-ratio iframe {
  bottom: 0;
  height: 100%;
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
  width: 100%
}
```
