### ISSUE TITLE
Chanson: post title capitalization is hardcoded, can't be changed in the editor

### ISSUE THREAD

**Issue by davewhitley** [Automattic/themes#8678]
### Quick summary

While using the Chanson theme I noticed that all the post titles have `text-transform: lowercase` applied. I tried to change this in the editor using the text transform controls, but I believe the theme's CSS is overriding everything I'm trying in the editor.

I tried changing the letter case on `text` styles and `heading` styles.

I would expect to see the lowercase option toggled on in the heading styles, and I would expect to be able to remove the text transform in the editor.

![Image](https://github.com/user-attachments/assets/341a7e3b-f2a5-416c-a1b4-ac913cf46f22)

![Image](https://github.com/user-attachments/assets/5fa4591f-9f74-440b-bf2c-1f1bc40d2ea7)

### Steps to reproduce

1. Go to Styles panel -> Typography -> Elements
2. Notice how the letter case option has nothing selected
3. Try to remove any letter case transformations
4. Notice how the preview doesn't change

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

**Comment by davewhitley** [comment]
```css
:root :where(.wp-block-post-title) {
font-size: var(--wp--preset--font-size--medium);
margin-bottom: 0;
text-transform: lowercase;
}
```
